# Generated by Django 2.2.14 on 2020-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cards', '0002_cardfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='cards', to='auth.Group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
