# Generated by Django 2.2.20 on 2021-05-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200730_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='development_en',
            field=models.TextField(blank=True, null=True, verbose_name='Development'),
        ),
        migrations.AddField(
            model_name='card',
            name='development_es',
            field=models.TextField(blank=True, null=True, verbose_name='Development'),
        ),
        migrations.AddField(
            model_name='card',
            name='development_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Development'),
        ),
        migrations.AddField(
            model_name='card',
            name='hint_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hints'),
        ),
        migrations.AddField(
            model_name='card',
            name='hint_es',
            field=models.TextField(blank=True, null=True, verbose_name='Hints'),
        ),
        migrations.AddField(
            model_name='card',
            name='hint_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Hints'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_certified_en',
            field=models.BooleanField(default=False, verbose_name='Card was certified'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_certified_es',
            field=models.BooleanField(default=False, verbose_name='Card was certified'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_certified_pt_br',
            field=models.BooleanField(default=False, verbose_name='Card was certified'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_public_en',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_public_es',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_public_pt_br',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='card',
            name='know_more_en',
            field=models.TextField(blank=True, null=True, verbose_name='Know More About'),
        ),
        migrations.AddField(
            model_name='card',
            name='know_more_es',
            field=models.TextField(blank=True, null=True, verbose_name='Know More About'),
        ),
        migrations.AddField(
            model_name='card',
            name='know_more_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Know More About'),
        ),
        migrations.AddField(
            model_name='card',
            name='lead_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='card',
            name='lead_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='card',
            name='lead_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='card',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='card',
            name='text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='card',
            name='text_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='card',
            name='you_will_need_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for this'),
        ),
        migrations.AddField(
            model_name='card',
            name='you_will_need_es',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for this'),
        ),
        migrations.AddField(
            model_name='card',
            name='you_will_need_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements for this'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_en',
            field=models.ImageField(null=True, upload_to='cards_images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_es',
            field=models.ImageField(null=True, upload_to='cards_images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_pt_br',
            field=models.ImageField(null=True, upload_to='cards_images/'),
        ),
    ]
