# Generated by Django 2.2.20 on 2021-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210505_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfile',
            name='file_en',
            field=models.FileField(null=True, upload_to='cards_files/'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='file_es',
            field=models.FileField(null=True, upload_to='cards_files/'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='file_pt_br',
            field=models.FileField(null=True, upload_to='cards_files/'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='cardfile',
            name='name_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
