# Generated by Django 2.2.28 on 2022-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20220610_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeembed',
            name='card_slide_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Card slide index'),
        ),
    ]
