# Generated by Django 2.2.28 on 2022-07-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_youtubeembed_card_slide_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_certified_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_certified_es',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_certified_pt_br',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_public_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_public_es',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_public_pt_br',
        ),
    ]
